### ISSUE TITLE
multiple-instances and haxe compilation server

### ISSUE THREAD

**Issue by nadako** [nadako/haxe-languageserver#3]
right now language server always starts haxe on the port 6000 which means it'll conflict when there are multiple instances of language server. we have to deal with this somehow.

i think it might be a good idea to just add support for haxe comp.server using stdio instead of socket.

**Comment by nadako** [comment]
@Simn @ousado

Could you guys maybe test this a bit:

https://github.com/nadako/haxe/tree/wait_stdio
https://github.com/nadako/haxe-languageserver/tree/wait_stdio

This uses stdin for arguments and stderr for output. It seems to work okay, but I'm concerned about wild `prerr_endline`s that can break something, so I'm thinking maybe we should prefix lines that come from the `Completion` exception with another one prefix (`\x03`).

This also fixes #7.

**Comment by Simn** [comment]
We don't usually have random `prerr_endline`s, but I also think it wouldn't hurt to cleanly prefix the messages.

**Comment by nadako** [comment]
I did a quick search for prerr and found some usages, but I guess that's only for the error cases (also DCE-debug, but that's not run on completion), so maybe it's okay after all.

What I'm not sure about now is the protocol. Currently, the stdin handling works just like the socket version - it read chunks and relies on the fact that the last one has `\x00` at the end. But the socket version disconnects after the transmission, while stdio is always connected, so I'm not sure it's safe to assume that chunk won't be somehow merged if the IDE quickly does two queries. Same question for the stderr output - I currently write `0` and flush stderr.

**Comment by nadako** [comment]
Okay, I have reworked the protocol, now it sends length first and then content both in and out. This should be more reliable.
