### ISSUE TITLE
Race condition when starting the Haxe server

### ISSUE THREAD

**Issue by RobDangerous** [nadako/haxe-languageserver#7]
For me everything works fine in Windows but when trying to use the VSCode extension in Linux it tries to connect to Haxe before that is up and running. Adding a setTimeout call after spawning Haxe fixes it for me. Proper fix would be to retry to connect regularly or use stdio as mentioned in #3.

**Comment by nadako** [comment]
Yeah, I think we gonna need to use stdio anyway, because socket server is too annoying to deal with (#3) and doing that should fix it.

I almost got it working BTW!

**Comment by nadako** [comment]
If you're interested in giving the stdio approach a try, see #3.

**Comment by RobDangerous** [comment]
Will do. Will merge it and force everyone to test.
